[project]
name = "med-lm-eval"
version = "0.1.0"
description = "Automated LLM evaluation suite for medical tasks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "verifiers>=0.1.3.post0",
]
