id: longhealth-t1-r2
module: longhealth
rollouts_per_example: 1
max_concurrent: 128
num_examples: -1
verbose: false
env_args:
  shuffle_answers: true
  shuffle_seed: 9331
  shuffle_docs_seed: 9331
  task: task1