id: longhealth-t2-r1
module: longhealth
rollouts_per_example: 1
max_concurrent: 128
num_examples: -1
verbose: false
env_args:
  shuffle_answers: true
  shuffle_seed: 1618
  shuffle_docs_seed: 1618
  task: task2