- id: medagentbenchv2_patient
  module: medagentbenchv2
  num_examples: -1
  verbose: false
  env_args:
    fhir_api_base: http://localhost:8080/fhir/
    tasks_variant: new_patient_tasks

- id: medagentbenchv2_test
  module: medagentbenchv2
  num_examples: -1
  verbose: false
  env_args:
    fhir_api_base: http://localhost:8080/fhir/
    tasks_variant: test_data_v2