id: medconceptsqa-sample-hard-r1
module: medconceptsqa
rollouts_per_example: 1
max_concurrent: 128
num_examples: -1
verbose: false
env_args:
  shuffle_answers: true
  shuffle_seed: 1618
  vocab: icd10cm_sample
  difficulty: hard
