- id: medcalc_bench
  module: medcalc_bench
  rollouts_per_example: 1
  verbose: false
  num_examples: -1
  env_args:
    version: "1.2"

- id: medcalc_bench_tools
  module: medcalc_bench
  rollouts_per_example: 1
  verbose: false
  num_examples: -1
  env_args:
    version: "verified"
    add_python_tool: true
    add_calculator_tool: true

  export:
    extra_columns: [lower_bound, upper_bound]
    answer_column: ground_truth