id: medconceptsqa-sample-easy-r2
module: medconceptsqa
rollouts_per_example: 1
max_concurrent: 128
num_examples: -1
verbose: false
env_args:
  shuffle_answers: true
  shuffle_seed: 9331
  vocab: icd10cm_sample
  difficulty: easy
