- id: medqa
  module: medqa
  rollouts_per_example: 1
  max_concurrent: 128
  num_examples: -1
  verbose: false

- id: medqa
  module: medqa
  rollouts_per_example: 1
  max_concurrent: 128
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
  matrix:
    shuffle_seed: [1618, 9331]
  matrix_id_format: "{base}-r{shuffle_seed}"
