- id: supergpqa_medicine
  module: supergpqa_medicine
  rollouts_per_example: 1
  num_examples: -1
  verbose: false
  matrix:
    difficulty: [easy, hard]
  matrix_id_format: "{base}-{difficulty}"

- id: supergpqa_medicine
  module: supergpqa_medicine
  rollouts_per_example: 1
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
    shuffle_seed: 1618
  matrix:
    difficulty: [easy, hard]
  matrix_id_format: "{base}-{difficulty}-rollout1618"

- id: supergpqa_medicine
  module: supergpqa_medicine
  rollouts_per_example: 1
  num_examples: -1
  verbose: false
  env_args:
    shuffle_answers: true
    shuffle_seed: 9331
  matrix:
    difficulty: [easy, hard]
  matrix_id_format: "{base}-{difficulty}-rollout9331"
