"""
ACI-BENCH Environment

This script defines an ACI-BENCH evaluation environment compatible with the Verifiers framework.
It supports two evaluation modes:
1. "judge" (Default): Uses an LLM-as-a-Judge to evaluate Accuracy, Completeness, and Clarity.
2. "metrics": Uses traditional NLP metrics (ROUGE, BERTScore, BLEURT).

Reference to the original paper and dataset:
@article{aci-bench,
  author = {Wen{-}wai Yim and Yujuan Fu and Asma {Ben Abacha} and Neal Snider and Thomas Lin and Meliha Yetisgen},
  title = {ACI-BENCH: a Novel Ambient Clinical Intelligence Dataset for Benchmarking Automatic Visit Note Generation},
  journal = {Nature Scientific Data},
  year = {2023}
}
"""

import os
import zipfile
import json
from pathlib import Path

import bert_score
import bleurt.score
import numpy as np
import verifiers as vf
from datasets import load_dataset
from rouge import Rouge
from openai import AsyncOpenAI

# NEW: Import the judge prompt template from the file we just created
from acibench_judge_prompts import JUDGE_TEMPLATE, JUDGE_OUTPUT_JSON


def medarc_cache_dir() -> Path:
    """Returns the path to the MedARC cache directory."""
    default_cache_path = Path.home() / ".cache" / "medarc"
    cache_dir = Path(os.getenv("MEDARC_CACHE_DIR", default_cache_path))
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir

def download_file(url: str, destination: Path):
    """Downloads a file from a URL to a destination, showing a progress bar."""
    import requests
    from tqdm import tqdm

    response = requests.get(url, stream=True)
    response.raise_for_status()
    total_size = int(response.headers.get("content-length", 0))

    with open(destination, "wb") as f, tqdm(
        desc=destination.name,
        total=total_size,
        unit="iB",
        unit_scale=True,
        unit_divisor=1024,
    ) as bar:
        for chunk in response.iter_content(chunk_size=8192):
            size = f.write(chunk)
            bar.update(size)

# --- Core Helper Functions ---

def _get_text_from_completion(completion: any) -> str:
    """Extracts a text string from a model completion."""
    if isinstance(completion, str):
        return completion
    if isinstance(completion, list) and completion:
        last_item = completion[-1]
        if isinstance(last_item, dict):
            return str(last_item.get("content", ""))
        return str(last_item)
    return str(completion)

def _extract_headers_from_note(note_text: str) -> list[str]:
    """Finds all lines in a note that are in ALL CAPS to use as section headers."""
    headers = []
    for line in note_text.splitlines():
        stripped_line = line.strip()
        if stripped_line and stripped_line.isupper():
            headers.append(stripped_line)
    return headers

def _build_context_aware_prompt(transcript: str, listener: str, writer: str, headers: list[str]) -> str:
    """Builds a tailored prompt based on the nature of the transcript."""
    base_prompt = "You are an expert medical scribe. Summarize the following conversation into a clinical note."
    
    if listener == 'virtscribe':
        base_prompt += " Crucially, the doctor will provide direct dictation commands. You must follow these for structure and content very closely."
    elif listener == 'virtassist':
        base_prompt += " Note that the doctor interacts with a Virtual Assistant; interpret these commands as context for the patient's condition."
    
    if writer == 'asr':
        base_prompt += " Warning: This transcript was generated by an ASR system and may contain transcription errors. Focus on key medical facts and ignore irrelevant chatter."
    
    header_list_str = ", ".join(headers)
    final_prompt = (
        f"{base_prompt}\n\n"
        f"Generate the note using these section headers in this exact order: {header_list_str}.\n\n"
        f"The conversation is:\n\n{transcript}"
    )
    return final_prompt


# --- Main Environment Loader ---

def load_environment(
    system_prompt: str | None = None,
    device: str | None = None,
    num_few_shot: int = 0,
    eval_method: str = "judge",
    judge_model: str = "gpt-4o",
    judge_base_url: str | None = None,
    judge_api_key: str | None = None,
) -> vf.Environment:
    """
    Loads the ACI-BENCH environment.

    Args:
        eval_method: 'judge' (default) for LLM-as-a-Judge or 'metrics' for ROUGE/BERTScore/BLEURT.
        judge_model: The model to use for LLM-as-a-Judge scoring.
        judge_base_url: Optional custom API URL for the judge.
        judge_api_key: Optional API key for the judge.
    """
    # Set CUDA device if specified
    if device and "cuda" in device:
        gpu_id = device.split(":")[-1]
        os.environ["CUDA_VISIBLE_DEVICES"] = gpu_id

    # Load and split dataset
    try:
        dataset = load_dataset("harsh-c137/aci-bench-medarc-eval", split="train")
        split_ds = dataset.train_test_split(test_size=0.2, seed=42)
        train_ds = split_ds["train"]
        val_ds = split_ds["test"]
    except Exception as e:
        raise ConnectionError(f"Could not load dataset. Error: {e}")

    # Prepare Evaluation Dataset
    def _map_example(example: dict) -> dict:
        headers = _extract_headers_from_note(example["note"])
        question = _build_context_aware_prompt(
            transcript=example["transcript"],
            listener=example["transcript_listener"],
            writer=example["transcript_writer"],
            headers=headers
        )
        
        # CRITICAL CHANGE: Pass original data to 'info' for the judge to use
        info = {
            "dialogue": example["transcript"],
            "reference_note": example["note"],
        }
        
        return {
            "question": question, 
            "answer": example["note"], 
            "info": info
        }

    original_columns = list(train_ds.features)
    train_mapped = train_ds.map(_map_example, remove_columns=original_columns)
    val_mapped = val_ds.map(_map_example, remove_columns=original_columns)

    # Prepare Few-Shot Examples
    few_shot_examples = []
    if num_few_shot > 0:
        few_shot_ds = train_ds.shuffle(seed=42).select(range(num_few_shot))
        for ex in few_shot_ds:
            headers = _extract_headers_from_note(ex["note"])
            user_content = _build_context_aware_prompt(ex["transcript"], ex["transcript_listener"], ex["transcript_writer"], headers)
            few_shot_examples.append({"role": "user", "content": user_content})
            few_shot_examples.append({"role": "assistant", "content": ex["note"]})

    # --- Rubric Construction ---
    parser = vf.Parser(extract_fn=_get_text_from_completion)
    final_rubric = vf.Rubric(parser=parser)

    # Initialize Metric Factories (Helpers defined below)
    rouge_factory = _create_rouge_reward_func()
    bertscore_factory = _create_bertscore_reward_func(device)
    bleurt_factory = _create_bleurt_reward_func()

    if eval_method == "judge":
        # Initialize Judge Client
        api_key = judge_api_key or os.getenv("JUDGE_API_KEY") or os.getenv("OPENAI_API_KEY")
        judge_client = AsyncOpenAI(base_url=judge_base_url, api_key=api_key)
        
        # Add Judge Reward (Primary)
        final_rubric.add_reward_func(
            _create_judge_reward_func(judge_client, judge_model),
            weight=1.0,
            name="judge_reward"
        )
        # Add Reference Metrics (Weight 0)
        final_rubric.add_reward_func(rouge_factory, weight=0, name="rouge")
        final_rubric.add_reward_func(bertscore_factory, weight=0, name="bertscore")
        final_rubric.add_reward_func(bleurt_factory, weight=0, name="bleurt")

    elif eval_method == "metrics":
        # Use Traditional Metrics
        final_rubric.add_reward_func(rouge_factory, weight=1.0, name="rouge")
        final_rubric.add_reward_func(bertscore_factory, weight=1.0, name="bertscore")
        final_rubric.add_reward_func(bleurt_factory, weight=1.0, name="bleurt")
    
    else:
        raise ValueError("eval_method must be one of 'judge' or 'metrics'")

    final_system_prompt = system_prompt or (
        "You are an expert medical scribe who generates clinical notes from doctor-patient conversations."
    )

    return vf.SingleTurnEnv(
        dataset=train_mapped,
        eval_dataset=val_mapped,
        few_shot=few_shot_examples,
        system_prompt=final_system_prompt,
        parser=parser,
        rubric=final_rubric,
    )


# --- Reward Function Factories ---

def _create_judge_reward_func(judge_client: AsyncOpenAI, judge_model: str):
    """Factory for the LLM-as-a-Judge reward function."""
    async def judge_reward(completion: any, info: dict, **kwargs) -> float:
        candidate_note = _get_text_from_completion(completion)
        dialogue = info.get("dialogue", "")
        reference_note = info.get("reference_note", "")

        # 1. Prepare Prompt
        judge_prompt = JUDGE_TEMPLATE.format(
            conversation=dialogue,
            candidate_note=candidate_note,
            reference_note=reference_note,
            output_format=JUDGE_OUTPUT_JSON
        )
        
        try:
            # 2. Call Judge API
            response = await judge_client.chat.completions.create(
                model=judge_model,
                messages=[{"role": "user", "content": judge_prompt}],
                temperature=0,
            )
            
            # 3. Parse Response
            judge_response_text = response.choices[0].message.content or ""
            # Basic cleanup for JSON parsing (handle markdown code blocks)
            if "```json" in judge_response_text:
                judge_response_text = judge_response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in judge_response_text:
                judge_response_text = judge_response_text.split("```")[1].split("```")[0].strip()

            scores = json.loads(judge_response_text)
            
            # 4. Calculate Normalized Score
            # Formula: Average of (accuracy/5 + completeness/5 + clarity/5)
            total_dims = 0
            accumulated = 0.0
            for dim in ["accuracy", "completeness", "clarity"]:
                dim_data = scores.get(dim, {})
                score = dim_data.get("score")
                
                # Handle potential string/int types
                if score is not None:
                    try:
                        score_val = float(score)
                        clamped = max(0.0, min(5.0, score_val))
                        accumulated += clamped / 5.0
                        total_dims += 1
                    except (ValueError, TypeError):
                        continue
            
            final_score = (accumulated / total_dims) if total_dims > 0 else 0.0
            return final_score

        except Exception as e:
            print(f"Judge evaluation failed: {e}")
            return 0.0
            
    return judge_reward


def _create_rouge_reward_func():
    rouge_scorer = Rouge()
    def rouge_reward(completion: any, answer: str, **kwargs) -> float:
        clean_completion = _get_text_from_completion(completion)
        if not clean_completion.strip() or not answer.strip(): return 0.0
        try:
            scores = rouge_scorer.get_scores(clean_completion, answer, avg=True)
            return float(np.mean([scores["rouge-1"]["f"], scores["rouge-2"]["f"], scores["rouge-l"]["f"]]))
        except Exception: return 0.0
    return rouge_reward

def _create_bertscore_reward_func(device: str | None):
    def bertscore_reward(completion: any, answer: str, **kwargs) -> float:
        clean_completion = _get_text_from_completion(completion)
        if not clean_completion.strip() or not answer.strip(): return 0.0
        _, _, f1 = bert_score.score(
            [clean_completion], [answer], lang="en", model_type="microsoft/deberta-xlarge-mnli", device=device
        )
        return f1.mean().item()
    return bertscore_reward

def _create_bleurt_reward_func():
    bleurt_checkpoint = medarc_cache_dir() / "acibench" / "bleurt-20"
    if not bleurt_checkpoint.exists():
        print("Downloading BLEURT-20 checkpoint (one-time setup)...")
        url = "https://storage.googleapis.com/bleurt-oss-21/BLEURT-20.zip"
        zip_path = bleurt_checkpoint.parent / f"{bleurt_checkpoint.name}.zip"
        bleurt_checkpoint.parent.mkdir(parents=True, exist_ok=True)
        download_file(url, zip_path)
        with zipfile.ZipFile(zip_path, "r") as z: z.extractall(bleurt_checkpoint.parent)
        zip_path.unlink()
    bleurt_scorer = bleurt.score.BleurtScorer(str(bleurt_checkpoint))
    
    def bleurt_reward(completion: any, answer: str, **kwargs) -> float:
        clean_completion = _get_text_from_completion(completion)
        if not clean_completion.strip() or not answer.strip(): return 0.0
        scores = bleurt_scorer.score(references=[answer], candidates=[clean_completion])
        return np.mean(scores)
    return bleurt_reward